### ISSUE TITLE
ResizeObserver not working in safari

### ISSUE THREAD

**Issue by kobbe82** [g787543/infinite-react-carousel#1]
The slider doesn't work in safari: ReferenceError: Can't find variable: ResizeObserver.
Using version 1.2.0

ResizeObserver class is not (native) implemented in safari so probably need to include the polyfill

**Comment by g787543** [comment]
Hi @kobbe82 

Thank you for your reply,
Give me a moment and let me see what the problem is.

**Comment by g787543** [comment]
I already pushed the new version on npm, please try again, thanks.

**Comment by kobbe82** [comment]
It works now, thanks!
