### ISSUE TITLE
SCRIPT438 Error in Internet Explorer 11.973

### ISSUE THREAD

**Issue by KartikSagar007** [g787543/infinite-react-carousel#11]
above carousel when I tried in IE 11 page is totally blank. :(

"Object doesn't support property or method 'forEach'"
"TypeError: Object doesn't support property or method 'forEach'
   at a (https://g787543.github.io/infinite-react-carousel/main.js:46:86254)
main.js (30,45709)

Looking for a new carousel :((

**Comment by g787543** [comment]
Hi, I already pushed the new version on npm, please try again.
