### ISSUE TITLE
Needs ForEach Polyfill

### ISSUE THREAD

**Issue by clayo** [g787543/infinite-react-carousel#14]
Does not support IE 11, get the error message "Object doesn't support property or method 'forEach'".  Adding react-app-polyfill and other polyfill offerings to project do not help... the issues is inside the carousel libraries where the polyfill libraries are not being imported.

Looks like this is specific to SPfx (SharePoint Framework) webparts.  The carousel works when standing on it's own, but put it into a SharePoint Framework webpart and the forEach calls all blow up internally to the infinite-react-carousel node_module.

**Comment by g787543** [comment]
Hi @clayo,

What is your package version?

**Comment by clayo** [comment]
Whatever the latest is.  Did an npm install on it yesterday.

Sent from my iPhone

Clay Osborn
Software Development Team Lead
direct 616-233-4554 | office (248) 412-8200
email cosborn@redlevelgroup.com | web redlevelgroup.com
Modern Workplace Webinar

On Feb 18, 2020, at 7:20 PM, Hans <notifications@github.com> wrote:

﻿

Hi @clayo<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclayo&data=02%7C01%7Ccosborn%40redlevelgroup.com%7C3c7e6c0b0a784f019f4808d7b4d1678a%7Cac56cd7ed609407a9eb4c77b623198f3%7C0%7C0%7C637176684243823322&sdata=3VYuHL8UVzvYgC%2B78TKcpZzNcfyY%2BQIfbIPrMt8X3TQ%3D&reserved=0>,

What is your package version?

**Comment by g787543** [comment]
Ok, I remove all of forEach. I will release later

**Comment by g787543** [comment]
I already release the new version on npm, please try again, Thanks.

**Comment by clayo** [comment]
That did the trick!!  That was some awesome response time.  Thank you!
