### ISSUE TITLE
Error: cannot create array

### ISSUE THREAD

**Issue by hariomssharmah** [g787543/infinite-react-carousel#19]
Get below error when try to use this control in one of my react project using SPFx framework:

Error: can not create array
    at new CircularArray (array.js:115)
    at Slider.<anonymous> (slider.js:208)
    at Yi (sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1)
    at $i (sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1)
    at Na (sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1)
    at Ma (sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1)
    at sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1
    at Object.Ay1f.t.unstable_runWithPriority (sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1)
    at wo (sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1)
    at xo (sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1)

Any help would be highly appreciated!

**Comment by lukaszewiczAd** [comment]
>Get below error when try to use this control in one of my react project using SPFx framework:

Did you solve it? @g787543, could you tell something about it? I have the same problem when I refresh the page with the Slider.

**Comment by hariomssharmah** [comment]
@lukaszewiczAd I had to use another control as I had time limitations. I used [slick-slider](https://kenwheeler.github.io/slick/) which seems much easier to extend and meets most of my requirements.

**Comment by pbassut** [comment]
Looks like you can't render this without any items. If you don't have any items to render inside the carousel, don't render the component at all. Kinda something the library should handle, but... this is the way it is.

**Comment by lorenamelor** [comment]
same problem here.

**Comment by danielbarion** [comment]
same problem here.

**Comment by Encoded77** [comment]
Also same problem

**Comment by pnkorn** [comment]
+

**Comment by andrey-samborskiy** [comment]
Hi, seems it can't works with empty array, but I'm not sure

**Comment by brianbentancourt** [comment]
I have the same problem. Solution?

**Comment by farhan-amjad** [comment]
this worked for me as i found that the slider component doesn't load immediately.

  const [isSlider, setisSlider] = useState(false)
  useEffect(()=>{
    setisSlider(true)
  },[])
  
  return (
  <div>
    {sliderVisible &&
      <Slider>
//slide items here
      </Slider>
     }
  </div>
);

**Comment by daniel-barbosaa** [comment]
> como o amigo @farhan-amjad disse, isso funcionou pra mim tbm, estava quebrando a cabeça com isso achei que teria que usar outra lib obrigado @farhan-amjad 
> 
> const [isSlider, setisSlider] = useState(false) useEffect(()=>{ setisSlider(true) },[])
> 
> retornar (
> 
> {sliderVisível & //deslize os itens aqui }
> );

**Comment by NicolasJEngler** [comment]
> this worked for me as i found that the slider component doesn't load immediately.
> 
> const [isSlider, setisSlider] = useState(false) useEffect(()=>{ setisSlider(true) },[])
> 
> return (
> {sliderVisible && //slide items here }
> );

As simple as it may seem, this was the solution for me.
