### ISSUE TITLE
Can we get a install guide for using with gatsby?

### ISSUE THREAD

**Issue by Palomino19** [g787543/infinite-react-carousel#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by g787543** [comment]
Hi, @Palomino19,

Thanks for your great advice. 
However, we don't have the plan to use gatsby in our project for now.

**Comment by g787543** [comment]
Hi, @Palomino19,

Thanks for your great advice.
However, we don't have the plan to use gatsby in our project for now.
